from fastapi import APIRouter

from app.api.v1.endpoints import (
    bonds,
    cashflows,
    cashflow_quality,
    companies,
    corporate_universe_action_plan,
    credit_risk,
    data_quality_dashboard,
    data_readiness,
    data_pipeline,
    datasets,
    financial_report_ingestion,
    financial_reports,
    health,
    imports,
    label_quality,
    live_data_readiness,
    market_data,
    market_history_quality,
    ml,
    ml_candidate_comparison,
    ml_candidate_strategy_robustness,
    ml_candidate_strategy_promotion,
    ml_evaluation,
    ml_prediction_quality,
    ml_validation_suite,
    ml_walk_forward,
    portfolio_construction,
    paper_trading,
    paper_trading_live_cycle,
    paper_trading_live_monitoring,
    paper_trading_live_pilot,
    paper_trading_live_readiness,
    paper_trading_live_schedule,
    scores,
    strategy_backtest,
    strategy_experiment,
    strategy_promotion,
    strategy_robustness,
)


api_router = APIRouter()
api_router.include_router(health.router, tags=["health"])
api_router.include_router(companies.router, prefix="/companies", tags=["companies"])
api_router.include_router(bonds.router, prefix="/bonds", tags=["bonds"])
api_router.include_router(cashflows.router, prefix="/cashflows", tags=["cashflows"])
api_router.include_router(scores.router, prefix="/scores", tags=["scores"])
api_router.include_router(
    credit_risk.router,
    prefix="/credit-risk",
    tags=["credit-risk"],
)
api_router.include_router(
    data_readiness.router,
    prefix="/data-readiness",
    tags=["data-readiness"],
)
api_router.include_router(
    live_data_readiness.router,
    prefix="/data-readiness",
    tags=["data-readiness-live"],
)
api_router.include_router(
    corporate_universe_action_plan.router,
    prefix="/data-readiness",
    tags=["data-readiness-corporate-universe"],
)
api_router.include_router(
    data_quality_dashboard.router,
    prefix="/data-quality",
    tags=["data-quality"],
)
api_router.include_router(
    cashflow_quality.router,
    prefix="/data-quality/cashflows",
    tags=["data-quality-cashflows"],
)
api_router.include_router(
    market_history_quality.router,
    prefix="/data-quality/market-history",
    tags=["data-quality-market-history"],
)
api_router.include_router(
    label_quality.router,
    prefix="/data-quality/labels",
    tags=["data-quality-labels"],
)
api_router.include_router(data_pipeline.router, prefix="/pipeline", tags=["pipeline"])
api_router.include_router(imports.router, prefix="/import", tags=["import"])
api_router.include_router(datasets.router, tags=["datasets"])
api_router.include_router(market_data.router, tags=["market-data"])
api_router.include_router(ml.router, prefix="/ml", tags=["ml"])
api_router.include_router(
    ml_validation_suite.router,
    prefix="/ml/validation-suite",
    tags=["ml-validation-suite"],
)
api_router.include_router(
    ml_walk_forward.router,
    prefix="/ml/walk-forward",
    tags=["ml-walk-forward"],
)
api_router.include_router(
    ml_evaluation.router,
    prefix="/ml/evaluation",
    tags=["ml-evaluation"],
)
api_router.include_router(
    ml_prediction_quality.router,
    prefix="/ml/evaluation/prediction-quality",
    tags=["ml-prediction-quality"],
)
api_router.include_router(
    ml_candidate_comparison.router,
    prefix="/ml/evaluation/candidates",
    tags=["ml-candidate-comparison"],
)
api_router.include_router(
    ml_candidate_strategy_promotion.router,
    prefix="/ml/evaluation/candidates",
    tags=["ml-candidate-strategy-promotion"],
)
api_router.include_router(
    ml_candidate_strategy_robustness.router,
    prefix="/ml/evaluation/candidates",
    tags=["ml-candidate-strategy-robustness"],
)
api_router.include_router(
    financial_report_ingestion.router,
    prefix="/financial-reports",
    tags=["financial-report-ingestion"],
)
api_router.include_router(
    financial_reports.router,
    prefix="/companies/{company_id}/reports",
    tags=["company-reports"],
)
api_router.include_router(
    strategy_backtest.router,
    prefix="/strategy/backtests",
    tags=["strategy-backtests"],
)
api_router.include_router(
    strategy_experiment.router,
    prefix="/strategy/experiments",
    tags=["strategy-experiments"],
)
api_router.include_router(
    strategy_promotion.router,
    prefix="/strategy/promotions",
    tags=["strategy-promotions"],
)
api_router.include_router(
    strategy_robustness.router,
    prefix="/strategy/robustness",
    tags=["strategy-robustness"],
)
api_router.include_router(
    portfolio_construction.router,
    prefix="/strategy/portfolio",
    tags=["strategy-portfolio"],
)
api_router.include_router(
    paper_trading.router,
    prefix="/paper-trading",
    tags=["paper-trading"],
)
api_router.include_router(
    paper_trading_live_readiness.router,
    prefix="/paper-trading/live",
    tags=["paper-trading-live-readiness"],
)
api_router.include_router(
    paper_trading_live_cycle.router,
    prefix="/paper-trading/live/cycles",
    tags=["paper-trading-live-cycles"],
)
api_router.include_router(
    paper_trading_live_schedule.router,
    prefix="/paper-trading/live/schedules",
    tags=["paper-trading-live-schedules"],
)
api_router.include_router(
    paper_trading_live_monitoring.router,
    prefix="/paper-trading/live/monitoring",
    tags=["paper-trading-live-monitoring"],
)
api_router.include_router(
    paper_trading_live_pilot.router,
    prefix="/paper-trading/live/pilots",
    tags=["paper-trading-live-pilots"],
)
